name: CI

on:
  pull_request:
  push:
    branches:
      - master

# Cancel a job if there's a new one on the same branch started.
# Based on https://stackoverflow.com/questions/58895283/stop-already-running-workflow-job-in-github-actions/67223051#67223051
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  # Faster crates.io index checkout.
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_LOG: debug

jobs:
  check_clippy:
    runs-on: ubuntu-24.04
    name: Clippy
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo clippy
        run: cargo clippy --all-targets --workspace --all-features -- -D warnings

  check_fmt:
    runs-on: ubuntu-24.04
    name: Checking fmt
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  rustdoc:
    runs-on: ubuntu-24.04
    name: Rustdoc
    steps:
      - uses: actions/checkout@v4
      - name: Run rustdoc
        run: cargo rustdoc --all-features -- -D warnings

  build:
    runs-on: ubuntu-24.04
    name: Release build
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo release build
        run: cargo build --release

  test_gpu:
    runs-on: ['self-hosted', 'linux', 'x64', '2xlarge+gpu']
    name: Test
    steps:
      - uses: actions/checkout@v4
      # TODO: Move the driver installation to the AMI.
      # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html
      # https://www.nvidia.com/en-us/drivers/
      - name: Install CUDA drivers
        run: |
          curl -L -o nvidia-driver-local-repo-ubuntu2404-570.148.08_1.0-1_amd64.deb https://us.download.nvidia.com/tesla/570.148.08/nvidia-driver-local-repo-ubuntu2404-570.148.08_1.0-1_amd64.deb
          sudo dpkg -i nvidia-driver-local-repo-ubuntu2404-570.148.08_1.0-1_amd64.deb
          sudo cp /var/nvidia-driver-local-repo-ubuntu2404-570.148.08/nvidia-driver-local-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes cuda-drivers
          rm nvidia-driver-local-repo-ubuntu2404-570.148.08_1.0-1_amd64.deb
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes libhwloc-dev nvidia-cuda-toolkit ocl-icd-opencl-dev
      # TODO: Remove this and other rust installation directives from jobs running
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: 1.83
      - name: Run tests
        run: cargo test
      - name: Run `add` example
        run: cargo run --example add
